function del_2_phi = del_2_phi(a,m,k)

% syms r theta

% del_2_phi = simplify((-a*(2^(1/2)*pi^(1/2)*besselj(m + 1/2, k*r) ...
%     *(2*m*sin(theta*(m - 1)) - k^2*r^2*sin(theta*(m - 1)) ...
%     + k^2*r^2*sin(theta*(m + 1))))-(2^(1/2)*pi^(1/2)*besseli(m + 1/2, k*r) ...
%     *(2*m*sin(theta*(m - 1)) + k^2*r^2*sin(theta*(m - 1)) ...
%     - k^2*r^2*sin(theta*(m + 1)))))/(4*k^2*r^4*sin(theta)*(1/(k*r))^(3/2)));

syms r theta
fun = (a*spherical_jn(m,k*r)+spherical_in(m,k*r))*cos(m*theta);

del_2_phi = simplify(diff(diff(fun,r),r)+2/r*diff(fun,r) ...
    +1/(r^2*sin(theta))*diff(sin(theta)*diff(fun,theta),theta),'Steps',10);